#!/bin/sh /etc/rc.common

USE_PROCD=1

br_is_querier() {
	local brport="$1"
	local has_snooping="`cat /sys/class/net/$brport/brport/bridge/bridge/multicast_snooping 2>/dev/null`"
	local has_querier="`cat /sys/class/net/$brport/brport/bridge/bridge/multicast_querier 2>/dev/null`"

	[ "$has_snooping" = "1" ] && [ "$has_querier" = "1" ] && \
		return 0

	return 1
}

check_blacklisted() {
	local iface="$1"
	local ret=0

	for blk in `uci get mldpoker.@blacklist[0].ifname`; do
		echo "$blk" | grep -q "^$iface\$" && {
			ret=1
			break
		}
	done

	return $ret
}

start_instance() {
	local iface="$1"
	local briface

	briface="`grep "INTERFACE" /sys/class/net/bat0/brport/bridge/uevent 2>/dev/null`"
	briface="${briface#*=}"

	check_blacklisted "$iface" || return

        procd_open_instance "mldpoker-$iface"
        procd_set_param command /usr/sbin/mldpoker $iface

        # respawn automatically if something died, be careful if you have an alternative process supervisor
        # if process dies sooner than respawn_threshold, it is considered crashed and after 5 retries the service is stopped
        procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}

        procd_set_param netdev $iface # likewise, except if dev's ifindex changes.
        procd_set_param stdout 0 # forward stdout of the command to logd
        procd_set_param stderr 1 # same for stderr
        procd_set_param pidfile /var/run/mldpoker-$iface.pid # write a pid file on instance start and remove it on stop
        procd_close_instance

	logger -t mldpoker "Starting mldpoker instance for $iface on $briface"
}

start_all_instances() {
	for brport in /sys/class/net/*/brport/; do
		brport=${brport%/*/}
		brport=${brport##*/}

		br_is_querier "$brport" || continue

		start_instance "$brport"
	done
}

start_service() {
	[ "`uci get mldpoker.@general[0].disabled 2> /dev/null`" = "1" ] && exit 0

	if [ $# -eq 0 ]; then
		start_all_instances
	elif [ $# -gt 0 ] && [ -n "$1" ]; then
		start_instance "$1"
	else
		echo "Error: Unknown start command: $@" >&2
		exit 1
	fi
}

stop_instance() {
	procd_kill mldpoker mldpoker-$1
}

stop_all_instances() {
	local brport

	for brport in /sys/class/net/*/brport/; do
		brport=${brport%/*/}
		brport=${brport##*/}

		br_is_querier "$brport" || continue

		stop_instance "$brport"
	done
}

stop_service() {
	if [ $# -eq 0 ]; then
		stop_all_instances
	elif [ $# -gt 0 ] && [ -n "$1" ]; then
		stop_instance "$1"
	else
		echo "Error: Unknown stop command: $@" >&2
		exit 1
	fi
}
